#!/usr/bin/env bash
set -euo pipefail

checker="$PWD/scripts/check-source-size.sh"
root=$(mktemp -d)
trap 'rm -rf "$root"' EXIT

make_lines() {
  local count=$1 path=$2
  mkdir -p "$(dirname "$path")"
  seq 1 "$count" > "$path"
}

mkdir -p "$root/backend/internal" "$root/frontend/src" "$root/deploy/scripts" "$root/scripts"
make_lines 400 "$root/backend/internal/at_limit.go"
make_lines 401 "$root/backend/internal/a.go"
make_lines 450 "$root/frontend/src/b.tsx"
make_lines 450 "$root/docs/ignored.md"
make_lines 450 "$root/deploy/scripts/provision.sql"

for ignored in node_modules vendor dist build coverage tmp generated; do
  make_lines 450 "$root/backend/$ignored/ignored.go"
done
make_lines 450 "$root/frontend/src/shared/api/generated/schema.ts"
{
  printf '// Code generated by fixture. DO NOT EDIT.\n'
  seq 2 450
} > "$root/backend/internal/generated.go"

if bash "$checker" "$root" >"$root/out" 2>&1; then
  echo 'expected source-size checker failure' >&2
  exit 1
fi
grep -q 'backend/internal/a.go — 401' "$root/out"
grep -q 'deploy/scripts/provision.sql — 450' "$root/out"
grep -q 'frontend/src/b.tsx — 450' "$root/out"
! grep -q 'at_limit.go' "$root/out"
! grep -q 'ignored' "$root/out"
! grep -q 'generated.go' "$root/out"
[[ "$(grep -n 'backend/internal/a.go' "$root/out" | cut -d: -f1)" -lt "$(grep -n 'frontend/src/b.tsx' "$root/out" | cut -d: -f1)" ]]

extensions_root=$(mktemp -d)
mkdir -p "$extensions_root/backend" "$extensions_root/frontend" "$extensions_root/deploy" "$extensions_root/scripts"
for extension in go ts tsx js jsx sql sh ps1; do
  make_lines 401 "$extensions_root/backend/oversized.$extension"
done
if bash "$checker" "$extensions_root" >"$extensions_root/out" 2>&1; then
  echo 'expected extension coverage failure' >&2
  exit 1
fi
[[ "$(grep -c 'oversized\.' "$extensions_root/out")" -eq 8 ]]
rm -rf "$extensions_root"
