$root = Join-Path ([IO.Path]::GetTempPath()) ('pharmacycrm-size-' + [guid]::NewGuid())
$extensionsRoot = Join-Path ([IO.Path]::GetTempPath()) ('pharmacycrm-size-extensions-' + [guid]::NewGuid())
$pwshExecutable = (Get-Process -Id $PID).Path

function Write-Lines([string] $Path, [int] $Count) {
    New-Item -ItemType Directory -Force -Path (Split-Path -Parent $Path) | Out-Null
    1..$Count | Set-Content -LiteralPath $Path
}

try {
    New-Item -ItemType Directory -Force -Path "$root/backend/internal", "$root/frontend/src", "$root/scripts", "$root/docs" | Out-Null
    Write-Lines "$root/backend/internal/at_limit.go" 400
    Write-Lines "$root/backend/internal/a.go" 401
    Write-Lines "$root/frontend/src/b.tsx" 450
    Write-Lines "$root/docs/ignored.md" 450

    foreach ($ignored in 'node_modules', 'vendor', 'dist', 'build', 'coverage', 'tmp', 'generated') {
        Write-Lines "$root/backend/$ignored/ignored.go" 450
    }
    Write-Lines "$root/frontend/src/shared/api/generated/schema.ts" 450
    @('// Code generated by fixture. DO NOT EDIT.') + (2..450) | Set-Content "$root/backend/internal/generated.go"

    $errorOutput = Join-Path $root 'size-errors.txt'
    $process = Start-Process -FilePath $pwshExecutable -ArgumentList '-NoProfile', '-File', "$PSScriptRoot/../check-source-size.ps1", '-Root', $root -Wait -PassThru -RedirectStandardError $errorOutput
    if ($process.ExitCode -ne 1) { throw 'expected size checker failure' }
    $text = Get-Content -Raw $errorOutput
    if ($text -notmatch 'backend/internal/a.go.*401' -or $text -notmatch 'frontend/src/b.tsx.*450') { throw "unexpected output: $text" }
    foreach ($unexpected in 'at_limit.go', 'ignored.go', 'schema.ts', 'generated.go') {
        if ($text -match [regex]::Escape($unexpected)) { throw "unexpected fixture in output: $unexpected" }
    }
    if ($text.IndexOf('backend/internal/a.go') -gt $text.IndexOf('frontend/src/b.tsx')) { throw 'output is not sorted' }

    New-Item -ItemType Directory -Force -Path "$extensionsRoot/backend", "$extensionsRoot/frontend", "$extensionsRoot/scripts" | Out-Null
    foreach ($extension in 'go', 'ts', 'tsx', 'js', 'jsx', 'sql', 'sh', 'ps1') {
        Write-Lines "$extensionsRoot/backend/oversized.$extension" 401
    }
    $extensionsOutput = Join-Path $extensionsRoot 'size-errors.txt'
    $process = Start-Process -FilePath $pwshExecutable -ArgumentList '-NoProfile', '-File', "$PSScriptRoot/../check-source-size.ps1", '-Root', $extensionsRoot -Wait -PassThru -RedirectStandardError $extensionsOutput
    if ($process.ExitCode -ne 1) { throw 'expected extension coverage failure' }
    $extensionText = Get-Content -Raw $extensionsOutput
    if ([regex]::Matches($extensionText, 'oversized\.').Count -ne 8) { throw "extension coverage is incomplete: $extensionText" }
} finally {
    Remove-Item -Recurse -Force $root, $extensionsRoot -ErrorAction SilentlyContinue
}
